#spring:
#  cloud:
#    config:
#      server:
#        native:
#           // 存放在本地目录下，每次更变内容需要重启config项目
#          search-locations: classpath:/shared
#  profiles:
#    active: native
spring:
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/homewin21/gitRository.git
          search-paths:
            - gitRository
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include:
          - bus-refresh