hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
server:
  port: 4000
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: file_route
          uri: lb://fileupload
          #          uri: http://localhost:8081
          predicates:
            - Path=/fileupload/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: hystrixCallBack
                fallbackUri: forward:/fallback

