hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:6000/getjwt
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user_route
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: myfallbackcmd
                fallbackUri: forward:/hystrix/fallback
        - id: file_route
          uri: lb://file-service
          #          uri: http://localhost:8081
          predicates:
            - Path=/file-service/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: myfallbackcmd
                fallbackUri: forward:/hystrix/fallback
server:
  port: 4000
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:6000/users/current
#    client:
#      id: client_2
#      client-secret: 123456
#      access-token-uri: http://localhost:6000/oauth/token
#      grant-type: client_credentials,password
#      scope: server


